services:
  glances-ical-api:
    build: .
    ports:
      - "8076:8076"
    restart: always
    environment:
      - ics_url=https://gist.githubusercontent.com/DeMarko/6142417/raw/1cd301a5917141524b712f92c2e955e86a1add19/sample.ics
